name = "badminton-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
workers_dev = true

routes = [
  { pattern = "badminton.dengjiabei.cn/api/*", zone_name = "dengjiabei.cn" }
]

[durable_objects]
bindings = [
  { name = "BADMINTON_ROOM", class_name = "BadmintonRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BadmintonRoom"]
